### PR TITLE
Update "download" dependency version

### PR DESCRIPTION
**Pull request by jbruni**
Fixes memory exposure security vulnerability:
https://nodesecurity.io/advisories/598

### CODE REVIEW

**Comment by jbruni** [comment]
I just got this warning from `npm audit`:

selection_247

- The issue is fixed at `tunnel-agent` version 0.6.0
- At version 2.0.1, the `caw` package updated its `tunnel-agent` dependency version to 0.6.0
- At version 7.0.0, 13 days ago, the `download` package updated its `caw` dependency version to 2.0.1

Now, to complete the chain, only `psi` needs to have its `download` dependency version updated.

**Comment by jbruni** [comment]
Hmm... well... `download` package version 7.0.0 uses JS syntax which is not supported by NodeJS 4.

In fact, `download` package version 7.0.0 requires NodeJS version >= 6

Thus, for this dependency update, `psi` requires Node.js 6

I have updated `package.json` and `.travis.yml` accordingly.

**Comment by anselmbradford** [comment]
I have a similar update [here](https://github.com/addyosmani/psi/pull/92). I just pulled in your node version updates.

**Comment by jbruni** [comment]
Thanks, @anselmbradford 

Closing this in favor of https://github.com/addyosmani/psi/pull/92

**Comment by anselmbradford** [comment]
Cool, thanks @jbruni … I'm worried this project is abandoned :(

**Pull request closed without merging**
